version: "3.8"

services:
  app:
    build: .
    image: hot-updater-bun
    ports:
      - "9090:9090"
    volumes:
      - ./assets:/app/assets
    environment:
      - NODE_ENV=production
      - PORT=9090
      - UPLOADS_DIR=assets/uploads
      - DB_PATH=assets/app.db