services:
  app:
    build: .
    image: hot-updater-bun
    ports:
      - "9292:9292"
    volumes:
      - ./assets:/app/assets
    environment:
      - NODE_ENV=production
      - APP_PORT=9292
      - APP_HOST=0.0.0.0
      - UPLOADS_DIR=assets/uploads
      - DB_PATH=assets/app.db